# Site settings
title: usunyu
email: usunyu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Life is like a box of chocolates, You never know what you're gonna get.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://usunyu.github.io/" # the base hostname & protocol for your site
facebook_username: yusun.io
twitter_username: Suny_o_O
github_username:  usunyu

# Build settings
markdown: kramdown
